export const palette = {
  light: {
    primary: '#1a3fbd',
    primaryForeground: '#ffffff',
    primaryLight: '#e8effd',
    background: '#f5f8ff',
    foreground: '#0e1929',
    card: '#ffffff',
    cardForeground: '#0e1929',
    border: '#cfd8e8',
    muted: '#eef0f5',
    mutedForeground: '#6b7b97',
    accent: '#e8effd',
    accentForeground: '#1a3fbd',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    success: '#10b981',
    successLight: '#d1fae5',
    warning: '#f59e0b',
    warningLight: '#fef3c7',
    info: '#3b82f6',
    infoLight: '#dbeafe',
    radius: 12,
  },
  dark: {
    primary: '#3b6ff5',
    primaryForeground: '#ffffff',
    primaryLight: '#1e2d52',
    background: '#0d1425',
    foreground: '#d4dff5',
    card: '#111c35',
    cardForeground: '#d4dff5',
    border: '#1e2d52',
    muted: '#14213d',
    mutedForeground: '#6b7a99',
    accent: '#1e2d52',
    accentForeground: '#d4dff5',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    success: '#10b981',
    successLight: '#064e3b',
    warning: '#f59e0b',
    warningLight: '#451a03',
    info: '#3b82f6',
    infoLight: '#1e3a5f',
    radius: 12,
  },
} as const;

export type ColorScheme = typeof palette.light;
