import type { ElementType } from "react";
import {
  LayoutDashboard, Box, GitBranch, Briefcase, FileText, MonitorPlay, Settings,
  ShoppingCart, ShoppingBag, UserCircle, Users, LayoutGrid, Mail, MailOpen,
  GanttChartSquare, MessageSquare, Layers, FolderOpen, Sparkles, Activity, Bot,
  Megaphone, Warehouse, Target, BarChart3, AlertTriangle, Clock, Calendar, Receipt,
  UserPlus, ScanLine, Factory, Database, TrendingUp, ListChecks, ClipboardList,
  Package, Phone, Cpu, Network, FlaskConical, TestTubes, CheckCircle2, CreditCard,
  PartyPopper, Ruler, Cog, Building2, PenLine, Zap, Grid3x3,
} from "lucide-react";

export interface NavMeta {
  icon: ElementType;
  color: string;
  bgColor: string;
}

/** Primary path → sidebar icon/colors (label comes from APP_MODULES). */
export const NAV_META: Record<string, NavMeta> = {
  "/": { icon: LayoutDashboard, color: "text-sky-400", bgColor: "bg-sky-500/15" },
  "/calendar": { icon: Calendar, color: "text-blue-400", bgColor: "bg-blue-500/15" },
  "/tasks": { icon: ClipboardList, color: "text-violet-400", bgColor: "bg-violet-500/15" },
  "/task-management": { icon: Activity, color: "text-purple-400", bgColor: "bg-purple-500/15" },
  "/team-pulse": { icon: Activity, color: "text-emerald-400", bgColor: "bg-emerald-500/15" },
  "/team-reporting": { icon: ClipboardList, color: "text-indigo-400", bgColor: "bg-indigo-500/15" },
  "/ip-call-logs": { icon: Phone, color: "text-cyan-400", bgColor: "bg-cyan-500/15" },
  "/ip-call-logs/hr": { icon: UserPlus, color: "text-emerald-400", bgColor: "bg-emerald-500/15" },
  "/ip-call-logs/project": { icon: Briefcase, color: "text-blue-400", bgColor: "bg-blue-500/15" },
  "/ip-call-logs/purchase": { icon: ShoppingCart, color: "text-amber-400", bgColor: "bg-amber-500/15" },
  "/ip-call-logs/marketing": { icon: Megaphone, color: "text-violet-400", bgColor: "bg-violet-500/15" },
  "/projects": { icon: Briefcase, color: "text-blue-400", bgColor: "bg-blue-500/15" },
  "/project-board": { icon: LayoutGrid, color: "text-indigo-400", bgColor: "bg-indigo-500/15" },
  "/project-timeline": { icon: GanttChartSquare, color: "text-cyan-400", bgColor: "bg-cyan-500/15" },
  "/meeting-minutes": { icon: FileText, color: "text-teal-400", bgColor: "bg-teal-500/15" },
  "/meeting-discussion": { icon: MessageSquare, color: "text-blue-400", bgColor: "bg-blue-500/15" },
  "/presentation": { icon: MonitorPlay, color: "text-orange-400", bgColor: "bg-orange-500/15" },
  "/speech-translator": { icon: MessageSquare, color: "text-violet-400", bgColor: "bg-violet-500/15" },
  "/translator": { icon: MessageSquare, color: "text-blue-400", bgColor: "bg-blue-500/15" },
  "/project-insights": { icon: BarChart3, color: "text-indigo-400", bgColor: "bg-indigo-500/15" },
  "/proposal-wizard": { icon: Sparkles, color: "text-blue-400", bgColor: "bg-blue-500/15" },
  "/proposal-library": { icon: FileText, color: "text-indigo-400", bgColor: "bg-indigo-500/15" },
  "/proposals": { icon: ClipboardList, color: "text-blue-400", bgColor: "bg-blue-500/15" },
  "/process-proposal": { icon: Layers, color: "text-sky-400", bgColor: "bg-sky-500/15" },
  "/design-3d": { icon: Box, color: "text-violet-400", bgColor: "bg-violet-500/15" },
  "/design-2d": { icon: PenLine, color: "text-blue-400", bgColor: "bg-blue-500/15" },
  "/step-part-drawings": { icon: Ruler, color: "text-sky-400", bgColor: "bg-sky-500/15" },
  "/pid": { icon: GitBranch, color: "text-rose-400", bgColor: "bg-rose-500/15" },
  "/nesting": { icon: Layers, color: "text-indigo-400", bgColor: "bg-indigo-500/15" },
  "/viewer-options": { icon: Settings, color: "text-slate-400", bgColor: "bg-slate-500/15" },
  "/project-drawings": { icon: FolderOpen, color: "text-sky-400", bgColor: "bg-sky-500/15" },
  "/approved-drawings": { icon: CheckCircle2, color: "text-emerald-400", bgColor: "bg-emerald-500/15" },
  "/drawings/mechanical": { icon: Cog, color: "text-blue-400", bgColor: "bg-blue-500/15" },
  "/drawings/electrical": { icon: Zap, color: "text-amber-400", bgColor: "bg-amber-500/15" },
  "/drawings/civil": { icon: Building2, color: "text-emerald-400", bgColor: "bg-emerald-500/15" },
  "/civil-drawing-ai": { icon: Sparkles, color: "text-purple-400", bgColor: "bg-purple-500/15" },
  "/material-request": { icon: ShoppingCart, color: "text-amber-400", bgColor: "bg-amber-500/15" },
  "/purchase-order": { icon: ShoppingBag, color: "text-orange-400", bgColor: "bg-orange-500/15" },
  "/purchase-orders": { icon: ShoppingBag, color: "text-orange-400", bgColor: "bg-orange-500/15" },
  "/purchase-dashboard": { icon: BarChart3, color: "text-blue-400", bgColor: "bg-blue-500/15" },
  "/stores-dashboard": { icon: Warehouse, color: "text-teal-400", bgColor: "bg-teal-500/15" },
  "/stock-reports": { icon: Package, color: "text-cyan-400", bgColor: "bg-cyan-500/15" },
  "/logistics-dashboard": { icon: Package, color: "text-cyan-400", bgColor: "bg-cyan-500/15" },
  "/finance-dashboard": { icon: Receipt, color: "text-emerald-400", bgColor: "bg-emerald-500/15" },
  "/email": { icon: Mail, color: "text-sky-400", bgColor: "bg-sky-500/15" },
  "/smart-inbox": { icon: Bot, color: "text-orange-400", bgColor: "bg-orange-500/15" },
  "/chat": { icon: MessageSquare, color: "text-blue-400", bgColor: "bg-blue-500/15" },
  "/sheets": { icon: Grid3x3, color: "text-green-400", bgColor: "bg-green-500/15" },
  "/marketing": { icon: Megaphone, color: "text-violet-400", bgColor: "bg-violet-500/15" },
  "/sales-dashboard": { icon: BarChart3, color: "text-emerald-400", bgColor: "bg-emerald-500/15" },
  "/sales": { icon: BarChart3, color: "text-emerald-400", bgColor: "bg-emerald-500/15" },
  "/leads": { icon: Target, color: "text-rose-400", bgColor: "bg-rose-500/15" },
  "/campaigns": { icon: BarChart3, color: "text-pink-400", bgColor: "bg-pink-500/15" },
  "/vc-card-scanner": { icon: ScanLine, color: "text-amber-400", bgColor: "bg-amber-500/15" },
  "/plant-enquiry": { icon: Factory, color: "text-blue-400", bgColor: "bg-blue-500/15" },
  "/hrms": { icon: UserCircle, color: "text-emerald-400", bgColor: "bg-emerald-500/15" },
  "/team": { icon: Users, color: "text-blue-400", bgColor: "bg-blue-500/15" },
  "/hrms/checkin": { icon: Clock, color: "text-teal-400", bgColor: "bg-teal-500/15" },
  "/hrms/leave-request": { icon: Calendar, color: "text-amber-400", bgColor: "bg-amber-500/15" },
  "/hrms/claims": { icon: Receipt, color: "text-violet-400", bgColor: "bg-violet-500/15" },
  "/hrms/recruitment": { icon: UserPlus, color: "text-blue-400", bgColor: "bg-blue-500/15" },
  "/hrms/incidents": { icon: AlertTriangle, color: "text-rose-400", bgColor: "bg-rose-500/15" },
  "/hrms/analytics": { icon: BarChart3, color: "text-indigo-400", bgColor: "bg-indigo-500/15" },
  "/hrms/performance": { icon: TrendingUp, color: "text-cyan-400", bgColor: "bg-cyan-500/15" },
  "/hrms/team-performance": { icon: Activity, color: "text-pink-400", bgColor: "bg-pink-500/15" },
  "/hrms/task-summary": { icon: ListChecks, color: "text-lime-400", bgColor: "bg-lime-500/15" },
  "/hrms/daily-reporting": { icon: ClipboardList, color: "text-orange-400", bgColor: "bg-orange-500/15" },
  "/hrms/work-monitor": { icon: Clock, color: "text-blue-400", bgColor: "bg-blue-500/15" },
  "/hrms/id-cards": { icon: CreditCard, color: "text-yellow-400", bgColor: "bg-yellow-500/15" },
  "/hrms/celebrations": { icon: PartyPopper, color: "text-pink-400", bgColor: "bg-pink-500/15" },
  "/site-data": { icon: Activity, color: "text-cyan-400", bgColor: "bg-cyan-500/15" },
  "/plant-overview": { icon: Activity, color: "text-cyan-400", bgColor: "bg-cyan-500/15" },
  "/site-db": { icon: Database, color: "text-indigo-400", bgColor: "bg-indigo-500/15" },
  "/site-db/analyze": { icon: Sparkles, color: "text-violet-400", bgColor: "bg-violet-500/15" },
  "/site-db/system": { icon: Database, color: "text-indigo-400", bgColor: "bg-indigo-500/15" },
  "/cctv": { icon: Activity, color: "text-slate-400", bgColor: "bg-slate-500/15" },
  "/gallery": { icon: FolderOpen, color: "text-sky-400", bgColor: "bg-sky-500/15" },
  "/workshop": { icon: Zap, color: "text-rose-500", bgColor: "bg-rose-500/15" },
  "/workshop/welder": { icon: Zap, color: "text-rose-500", bgColor: "bg-rose-500/15" },
  "/workshop/fitter": { icon: Activity, color: "text-blue-400", bgColor: "bg-blue-500/15" },
  "/om/chemical-consumption": { icon: FlaskConical, color: "text-emerald-400", bgColor: "bg-emerald-500/15" },
  "/om/lab-reports": { icon: TestTubes, color: "text-blue-400", bgColor: "bg-blue-500/15" },
  "/om/site-performance": { icon: BarChart3, color: "text-indigo-400", bgColor: "bg-indigo-500/15" },
  "/plc-automation/device-config": { icon: Cpu, color: "text-sky-400", bgColor: "bg-sky-500/15" },
  "/plc-automation/site-calls": { icon: Phone, color: "text-cyan-400", bgColor: "bg-cyan-500/15" },
  "/plc-automation/service-reports": { icon: ClipboardList, color: "text-blue-400", bgColor: "bg-blue-500/15" },
  "/plc-automation/plc-programs": { icon: Cpu, color: "text-sky-400", bgColor: "bg-sky-500/15" },
  "/plc-automation/hmi-programs": { icon: MonitorPlay, color: "text-violet-400", bgColor: "bg-violet-500/15" },
  "/plc-automation/pid-design": { icon: GitBranch, color: "text-rose-400", bgColor: "bg-rose-500/15" },
  "/plc-automation/instruments": { icon: Activity, color: "text-teal-400", bgColor: "bg-teal-500/15" },
  "/plc-automation/tags": { icon: Target, color: "text-amber-400", bgColor: "bg-amber-500/15" },
  "/plc-automation/panel-inspection": { icon: ClipboardList, color: "text-orange-400", bgColor: "bg-orange-500/15" },
  "/plc-automation/support-tickets": { icon: FileText, color: "text-violet-400", bgColor: "bg-violet-500/15" },
  "/plc-automation/network-architecture": { icon: Network, color: "text-blue-400", bgColor: "bg-blue-500/15" },
  "/mis-report": { icon: BarChart3, color: "text-violet-400", bgColor: "bg-violet-500/15" },
  "/payment-tracker": { icon: Receipt, color: "text-indigo-400", bgColor: "bg-indigo-500/15" },
  "/user-management": { icon: Users, color: "text-red-400", bgColor: "bg-red-500/15" },
  "/agent-management": { icon: UserCircle, color: "text-violet-400", bgColor: "bg-violet-500/15" },
  "/settings": { icon: Settings, color: "text-slate-400", bgColor: "bg-slate-500/15" },
  "/email-settings": { icon: MailOpen, color: "text-sky-400", bgColor: "bg-sky-500/15" },
};

const DEFAULT_META: NavMeta = {
  icon: FileText,
  color: "text-slate-400",
  bgColor: "bg-slate-500/15",
};

export function navMetaForPath(path: string): NavMeta {
  return NAV_META[path] ?? DEFAULT_META;
}
