import { Router } from "express";
import PDFDocument from "pdfkit";
import { randomUUID } from "crypto";

const router = Router();

const ERP_URL = process.env.ERPNEXT_URL?.replace(/\/$/, "");
const auth = () => `token ${process.env.ERPNEXT_API_KEY}:${process.env.ERPNEXT_API_SECRET}`;
function isConfigured() { return !!(ERP_URL && process.env.ERPNEXT_API_KEY && process.env.ERPNEXT_API_SECRET); }

const ULTRAMSG_INSTANCE = "instance149987";
const ULTRAMSG_TOKEN = "6baxh4iuxajibxez";
const REPORT_WHATSAPP_TO = "919698109426";

// ─── In-memory PDF store (TTL: 5 min) ─────────────────────────────────────────
const pdfStore = new Map<string, { buf: Buffer; filename: string; expires: number }>();
setInterval(() => {
  const now = Date.now();
  for (const [k, v] of pdfStore) if (v.expires < now) pdfStore.delete(k);
}, 60_000);

// ─── PDF generation ────────────────────────────────────────────────────────────
const SKIP = new Set(["doctype","idx","docstatus","__islocal","__unsaved","owner","__last_sync_on",
  "name","employee","employee_name","department","date","status",
  "modified","modified_by","creation","amended_from"]);
const CHILD_SKIP = new Set([...SKIP, "parent","parenttype","parentfield"]);

function generateReportPDF(report: any): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 40, bufferPages: true });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const dept = (report.department || "").replace(/ - WTT$/i, "");
    const dateStr = report.date
      ? new Date(report.date + "T00:00:00").toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" })
      : "";

    // Header band
    doc.rect(0, 0, doc.page.width, 70).fill("#1a3a5c");
    doc.fillColor("white").fontSize(20).font("Helvetica-Bold").text("Daily Report", 40, 18);
    doc.fontSize(10).font("Helvetica").text("FlowMatriX — WTT International", 40, 44);
    doc.moveDown(3);

    // Employee info box
    doc.fillColor("#f0f4f8").rect(40, 80, doc.page.width - 80, 52).fill();
    doc.fillColor("#1a3a5c").fontSize(14).font("Helvetica-Bold")
      .text(report.employee_name || report.employee || "", 50, 90);
    const meta: string[] = [];
    if (dept) meta.push(dept);
    if (dateStr) meta.push(dateStr);
    if (report.status) meta.push(`Status: ${report.status}`);
    doc.fillColor("#4a6080").fontSize(9).font("Helvetica").text(meta.join("   •   "), 50, 109);
    doc.y = 148;

    // Section helper
    function section(title: string) {
      doc.moveDown(0.6);
      doc.fillColor("#1a3a5c").fontSize(11).font("Helvetica-Bold").text(title.toUpperCase());
      doc.moveTo(40, doc.y + 2).lineTo(doc.page.width - 40, doc.y + 2)
        .strokeColor("#3b82f6").lineWidth(1.2).stroke();
      doc.moveDown(0.4);
    }

    function labelValue(label: string, value: string) {
      const x = 40; const colW = 160;
      doc.fontSize(9).font("Helvetica-Bold").fillColor("#334155")
        .text(label + ":", x, doc.y, { width: colW, continued: true });
      doc.font("Helvetica").fillColor("#1e293b")
        .text(" " + value, { width: doc.page.width - 80 - colW });
    }

    // Scalar fields
    const scalars = Object.entries(report).filter(
      ([k, v]) => !SKIP.has(k) && !Array.isArray(v) && v !== null && v !== "" && v !== 0
    );
    if (scalars.length) {
      section("Details");
      scalars.forEach(([k, v]) => labelValue(k.replace(/_/g, " "), String(v)));
    }

    // Child tables
    const tables = Object.entries(report).filter(
      ([, v]) => Array.isArray(v) && (v as any[]).length > 0
    );
    tables.forEach(([key, rows]) => {
      section(key.replace(/_/g, " "));
      (rows as any[]).forEach((row: any, i: number) => {
        const entries = Object.entries(row).filter(
          ([k, v]) => !CHILD_SKIP.has(k) && v !== null && v !== "" && v !== 0
        );
        if (!entries.length) return;
        doc.fillColor("#e2e8f0").rect(40, doc.y, doc.page.width - 80, 16).fill();
        doc.fillColor("#1e3a5f").fontSize(9).font("Helvetica-Bold")
          .text(`  ${i + 1}.`, 42, doc.y + 3, { width: 30 });
        const firstEntry = entries.shift()!;
        doc.text(`${firstEntry[0].replace(/_/g, " ")}: ${firstEntry[1]}`, 72, doc.y + 3, { width: doc.page.width - 120 });
        doc.moveDown(0.3);
        entries.forEach(([k, v]) => {
          doc.fillColor("#475569").fontSize(8.5).font("Helvetica")
            .text(`    ${k.replace(/_/g, " ")}: ${v}`, 52, doc.y, { width: doc.page.width - 100 });
        });
        doc.moveDown(0.2);
      });
    });

    // Footer
    const footerY = doc.page.height - 35;
    doc.rect(0, footerY - 5, doc.page.width, 40).fill("#f0f4f8");
    doc.fillColor("#94a3b8").fontSize(8).font("Helvetica")
      .text(`Generated by FlowMatriX  •  ${new Date().toLocaleString("en-GB")}`,
        40, footerY, { align: "center", width: doc.page.width - 80 });

    doc.end();
  });
}

// ─── Send document via UltraMsg ────────────────────────────────────────────────
async function sendWhatsAppDocument(to: string, docUrl: string, filename: string, caption: string): Promise<{ success: boolean; error?: string }> {
  try {
    const params = new URLSearchParams({ token: ULTRAMSG_TOKEN, to, document: docUrl, filename, caption, priority: "10" });
    const res = await fetch(`https://api.ultramsg.com/${ULTRAMSG_INSTANCE}/messages/document`, {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: params.toString(),
    });
    const data = await res.json() as Record<string, unknown>;
    if (data.sent === "true" || data.sent === true) return { success: true };
    return { success: false, error: JSON.stringify(data) };
  } catch (e) {
    return { success: false, error: String(e) };
  }
}

// Map Frappe docstatus integer to a human-readable label
function mapDocStatus(docstatus: number): string {
  if (docstatus === 1) return "Submitted";
  if (docstatus === 2) return "Cancelled";
  return "Draft";
}

// ─── List Daily Reports ───────────────────────────────────────────────────────
// IMPORTANT: Frappe blocks many field names as SQL reserved keywords in get_list:
//   "date", "status", "type", "order", "group", "key", "value", "interval" …
// Solution: only request guaranteed-safe meta fields, use docstatus for status,
// derive the date from the document name or creation timestamp,
// and do all filtering server-side.
router.get("/daily-reporting", async (req, res) => {
  if (!isConfigured()) return res.status(503).json({ error: "ERPNext not configured" });

  const { from_date, to_date, employee, department, status, limit = "30", page = "0" } = req.query as Record<string, string>;

  try {
    // Only safe Frappe meta fields that don't conflict with SQL reserved words
    const fields = JSON.stringify([
      "name", "employee", "employee_name", "department",
      "docstatus", "modified", "creation",
    ]);

    // No ERPNext-side filters — all filtering done server-side to avoid keyword conflicts
    const params = new URLSearchParams({
      fields,
      limit_page_length: "500",
      limit_start: "0",
      order_by: "creation desc",
    });

    const r = await fetch(`${ERP_URL}/api/resource/Daily Reporting?${params}`, {
      headers: { Authorization: auth() },
    });

    if (!r.ok) {
      const text = await r.text().catch(() => "");
      return res.status(r.status).json({ error: `ERPNext error: ${text.slice(0, 300)}` });
    }

    const json = await r.json() as { data: any[] };
    let rows: any[] = (json.data || []).map(row => ({
      ...row,
      // Derive date from document name (e.g. DR-2026-03-01) or creation timestamp
      date: row.name?.match(/(\d{4}-\d{2}-\d{2})/)?.[1] || row.creation?.split(" ")[0] || null,
      // Map numeric docstatus to readable label
      status: mapDocStatus(row.docstatus),
    }));

    // Server-side filtering
    if (from_date) rows = rows.filter(r => r.date && r.date >= from_date);
    if (to_date)   rows = rows.filter(r => r.date && r.date <= to_date);
    if (employee)  rows = rows.filter(r => (r.employee_name || r.employee || "").toLowerCase().includes((employee as string).toLowerCase()));
    if (department) rows = rows.filter(r => (r.department || "").toLowerCase().includes((department as string).toLowerCase()));
    if (status)    rows = rows.filter(r => r.status === status);

    // Sort by derived date desc
    rows.sort((a, b) => (b.date || b.creation || "").localeCompare(a.date || a.creation || ""));

    // Paginate
    const pageNum = Number(page);
    const pageSize = Number(limit);
    const start = pageNum * pageSize;
    const paged = rows.slice(start, start + pageSize + 1);
    const hasMore = paged.length > pageSize;

    res.json({ reports: paged.slice(0, pageSize), hasMore, total: rows.length });
  } catch (e) {
    res.status(500).json({ error: String(e) });
  }
});

// ─── Create New Daily Report ─────────────────────────────────────────────────
router.post("/daily-reporting", async (req, res) => {
  if (!isConfigured()) return res.status(503).json({ error: "ERPNext not configured" });

  const { employee_name, date, activities = [] } = req.body;
  if (!employee_name || !date) return res.status(400).json({ error: "employee_name and date are required" });

  try {
    const docData: any = {
      doctype: "Daily Reporting",
      employee_name,
      date,
    };

    // Add activities as child table if provided
    if (Array.isArray(activities) && activities.length > 0) {
      const validRows = activities.filter(a => a.activity || a.project);
      if (validRows.length > 0) {
        docData.daily_reporting_detail = validRows.map((a: any) => ({
          doctype: "Daily Reporting Detail",
          activity: a.activity || "",
          project: a.project || "",
          no_of_hours: parseFloat(a.hours) || 0,
          remarks: a.remarks || "",
        }));
      }
    }

    const r = await fetch(`${ERP_URL}/api/resource/Daily Reporting`, {
      method: "POST",
      headers: { Authorization: auth(), "Content-Type": "application/json" },
      body: JSON.stringify(docData),
    });

    const json = await r.json() as any;
    if (!r.ok) return res.status(r.status).json({ error: json.exception || json.message || "Failed to create" });

    res.json({ name: json.data?.name, success: true });
  } catch (e) {
    res.status(500).json({ error: String(e) });
  }
});

// ─── Serve a temporarily stored PDF ───────────────────────────────────────────
router.get("/daily-reporting/pdf/:id", (req, res) => {
  const entry = pdfStore.get(req.params.id);
  if (!entry) return res.status(404).json({ error: "PDF not found or expired" });
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `inline; filename="${entry.filename}"`);
  res.send(entry.buf);
});

// ─── Send Report as PDF via WhatsApp (UltraMsg) ────────────────────────────────
router.post("/daily-reporting/:name/send-whatsapp", async (req, res) => {
  if (!isConfigured()) return res.status(503).json({ error: "ERPNext not configured" });

  const { name } = req.params;
  const to: string = req.body.to || REPORT_WHATSAPP_TO;

  try {
    // Fetch full document from ERPNext
    const r = await fetch(`${ERP_URL}/api/resource/Daily Reporting/${encodeURIComponent(name)}`, {
      headers: { Authorization: auth() },
    });
    if (!r.ok) return res.status(r.status).json({ error: "Report not found" });
    const json = await r.json() as { data: any };
    const report = json.data;

    // Generate PDF
    const pdfBuf = await generateReportPDF(report);
    const id = randomUUID();
    const empName = (report.employee_name || report.employee || "report").replace(/\s+/g, "_");
    const dateTag = (report.date || new Date().toISOString().slice(0, 10)).replace(/-/g, "");
    const filename = `DailyReport_${empName}_${dateTag}.pdf`;
    pdfStore.set(id, { buf: pdfBuf, filename, expires: Date.now() + 5 * 60_000 });

    // Build a publicly accessible URL using the Replit dev domain
    const host = process.env.REPLIT_DEV_DOMAIN
      ? `https://${process.env.REPLIT_DEV_DOMAIN}`
      : `http://localhost:${process.env.PORT || 8080}`;
    const pdfUrl = `${host}/api/daily-reporting/pdf/${id}`;

    const dept = (report.department || "").replace(/ - WTT$/i, "");
    const dateStr = report.date
      ? new Date(report.date + "T00:00:00").toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" })
      : "";
    const caption = [`Daily Report — ${report.employee_name || report.employee || ""}`,
      dept, dateStr, `Status: ${report.status || "Draft"}`].filter(Boolean).join("  |  ");

    const result = await sendWhatsAppDocument(to, pdfUrl, filename, caption);

    if (result.success) {
      res.json({ success: true, to, filename });
    } else {
      res.status(502).json({ success: false, error: result.error || "WhatsApp send failed" });
    }
  } catch (e) {
    res.status(500).json({ error: String(e) });
  }
});

// ─── Single Daily Report Detail ───────────────────────────────────────────────
// Single document fetch uses a different Frappe endpoint that doesn't have the
// same field-name restrictions as get_list.
router.get("/daily-reporting/:name", async (req, res) => {
  if (!isConfigured()) return res.status(503).json({ error: "ERPNext not configured" });

  const { name } = req.params;
  try {
    const r = await fetch(`${ERP_URL}/api/resource/Daily Reporting/${encodeURIComponent(name)}`, {
      headers: { Authorization: auth() },
    });

    if (!r.ok) return res.status(r.status).json({ error: "Report not found" });

    const json = await r.json() as { data: any };
    res.json({ report: json.data });
  } catch (e) {
    res.status(500).json({ error: String(e) });
  }
});

export default router;
