import { Router } from "express";
import PDFDocument from "pdfkit";
import { randomUUID } from "crypto";

const router = Router();

const ERP_URL = process.env.ERPNEXT_URL?.replace(/\/$/, "");
const auth = () => `token ${process.env.ERPNEXT_API_KEY}:${process.env.ERPNEXT_API_SECRET}`;
function isConfigured() { return !!(ERP_URL && process.env.ERPNEXT_API_KEY && process.env.ERPNEXT_API_SECRET); }

const ULTRAMSG_INSTANCE = "instance149987";
const ULTRAMSG_TOKEN = "6baxh4iuxajibxez";
const REPORT_WHATSAPP_TO = "919698109426";

// ─── In-memory PDF store (TTL: 5 min) ─────────────────────────────────────────
const pdfStore = new Map<string, { buf: Buffer; filename: string; expires: number }>();
setInterval(() => {
  const now = Date.now();
  for (const [k, v] of pdfStore) if (v.expires < now) pdfStore.delete(k);
}, 60_000);

// ─── PDF generation ────────────────────────────────────────────────────────────
const SKIP = new Set(["doctype","idx","docstatus","__islocal","__unsaved","owner","__last_sync_on",
  "name","employee","employee_name","department","date","status",
  "modified","modified_by","creation","amended_from"]);
const CHILD_SKIP = new Set([...SKIP, "parent","parenttype","parentfield"]);

function generateReportPDF(report: any): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 40, bufferPages: true });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const dept = (report.department || "").replace(/ - WTT$/i, "");
    const dateStr = report.date
      ? new Date(report.date + "T00:00:00").toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" })
      : "";

    // Header band
    doc.rect(0, 0, doc.page.width, 70).fill("#1a3a5c");
    doc.fillColor("white").fontSize(20).font("Helvetica-Bold").text("Daily Report", 40, 18);
    doc.fontSize(10).font("Helvetica").text("FlowMatriX — WTT International", 40, 44);
    doc.moveDown(3);

    // Employee info box
    doc.fillColor("#f0f4f8").rect(40, 80, doc.page.width - 80, 52).fill();
    doc.fillColor("#1a3a5c").fontSize(14).font("Helvetica-Bold")
      .text(report.employee_name || report.employee || "", 50, 90);
    const meta: string[] = [];
    if (dept) meta.push(dept);
    if (dateStr) meta.push(dateStr);
    if (report.status) meta.push(`Status: ${report.status}`);
    doc.fillColor("#4a6080").fontSize(9).font("Helvetica").text(meta.join("   •   "), 50, 109);
    doc.y = 148;

    // Section helper
    function section(title: string) {
      doc.moveDown(0.6);
      doc.fillColor("#1a3a5c").fontSize(11).font("Helvetica-Bold").text(title.toUpperCase());
      doc.moveTo(40, doc.y + 2).lineTo(doc.page.width - 40, doc.y + 2)
        .strokeColor("#3b82f6").lineWidth(1.2).stroke();
      doc.moveDown(0.4);
    }

    function labelValue(label: string, value: string) {
      const x = 40; const colW = 160;
      doc.fontSize(9).font("Helvetica-Bold").fillColor("#334155")
        .text(label + ":", x, doc.y, { width: colW, continued: true });
      doc.font("Helvetica").fillColor("#1e293b")
        .text(" " + value, { width: doc.page.width - 80 - colW });
    }

    // Scalar fields
    const scalars = Object.entries(report).filter(
      ([k, v]) => !SKIP.has(k) && !Array.isArray(v) && v !== null && v !== "" && v !== 0
    );
    if (scalars.length) {
      section("Details");
      scalars.forEach(([k, v]) => labelValue(k.replace(/_/g, " "), String(v)));
    }

    // Child tables
    const tables = Object.entries(report).filter(
      ([, v]) => Array.isArray(v) && (v as any[]).length > 0
    );
    tables.forEach(([key, rows]) => {
      section(key.replace(/_/g, " "));
      (rows as any[]).forEach((row: any, i: number) => {
        const entries = Object.entries(row).filter(
          ([k, v]) => !CHILD_SKIP.has(k) && v !== null && v !== "" && v !== 0
        );
        if (!entries.length) return;
        doc.fillColor("#e2e8f0").rect(40, doc.y, doc.page.width - 80, 16).fill();
        doc.fillColor("#1e3a5f").fontSize(9).font("Helvetica-Bold")
          .text(`  ${i + 1}.`, 42, doc.y + 3, { width: 30 });
        const firstEntry = entries.shift()!;
        doc.text(`${firstEntry[0].replace(/_/g, " ")}: ${firstEntry[1]}`, 72, doc.y + 3, { width: doc.page.width - 120 });
        doc.moveDown(0.3);
        entries.forEach(([k, v]) => {
          doc.fillColor("#475569").fontSize(8.5).font("Helvetica")
            .text(`    ${k.replace(/_/g, " ")}: ${v}`, 52, doc.y, { width: doc.page.width - 100 });
        });
        doc.moveDown(0.2);
      });
    });

    // Footer
    const footerY = doc.page.height - 35;
    doc.rect(0, footerY - 5, doc.page.width, 40).fill("#f0f4f8");
    doc.fillColor("#94a3b8").fontSize(8).font("Helvetica")
      .text(`Generated by FlowMatriX  •  ${new Date().toLocaleString("en-GB")}`,
        40, footerY, { align: "center", width: doc.page.width - 80 });

    doc.end();
  });
}

// ─── Send document via UltraMsg ────────────────────────────────────────────────
async function sendWhatsAppDocument(to: string, docUrl: string, filename: string, caption: string): Promise<{ success: boolean; error?: string }> {
  try {
    const params = new URLSearchParams({ token: ULTRAMSG_TOKEN, to, document: docUrl, filename, caption, priority: "10" });
    const res = await fetch(`https://api.ultramsg.com/${ULTRAMSG_INSTANCE}/messages/document`, {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: params.toString(),
    });
    const data = await res.json() as Record<string, unknown>;
    if (data.sent === "true" || data.sent === true) return { success: true };
    return { success: false, error: JSON.stringify(data) };
  } catch (e) {
    return { success: false, error: String(e) };
  }
}

// Map Frappe docstatus integer to a human-readable label
function mapDocStatus(docstatus: number): string {
  if (docstatus === 1) return "Submitted";
  if (docstatus === 2) return "Cancelled";
  return "Draft";
}

// ─── List Daily Reports ───────────────────────────────────────────────────────
// IMPORTANT: Frappe blocks many field names as SQL reserved keywords in get_list:
//   "date", "status", "type", "order", "group", "key", "value", "interval" …
// Solution: only request guaranteed-safe meta fields, use docstatus for status,
// derive the date from the document name or creation timestamp,
// and do all filtering server-side.
router.get("/daily-reporting", async (req, res) => {
  if (!isConfigured()) return res.status(503).json({ error: "ERPNext not configured" });

  const { from_date, to_date, employee, department, status, limit = "30", page = "0" } = req.query as Record<string, string>;

  try {
    // Only safe Frappe meta fields that don't conflict with SQL reserved words
    const fields = JSON.stringify([
      "name", "employee", "employee_name", "department",
      "docstatus", "modified", "creation",
    ]);

    // No ERPNext-side filters — all filtering done server-side to avoid keyword conflicts
    const params = new URLSearchParams({
      fields,
      limit_page_length: "500",
      limit_start: "0",
      order_by: "creation desc",
    });

    const r = await fetch(`${ERP_URL}/api/resource/Daily Reporting?${params}`, {
      headers: { Authorization: auth() },
    });

    if (!r.ok) {
      const text = await r.text().catch(() => "");
      return res.status(r.status).json({ error: `ERPNext error: ${text.slice(0, 300)}` });
    }

    const json = await r.json() as { data: any[] };
    let rows: any[] = (json.data || []).map(row => ({
      ...row,
      // Derive date from document name (e.g. DR-2026-03-01) or creation timestamp
      date: row.name?.match(/(\d{4}-\d{2}-\d{2})/)?.[1] || row.creation?.split(" ")[0] || null,
      // Map numeric docstatus to readable label
      status: mapDocStatus(row.docstatus),
    }));

    // Server-side filtering
    if (from_date) rows = rows.filter(r => r.date && r.date >= from_date);
    if (to_date)   rows = rows.filter(r => r.date && r.date <= to_date);
    if (employee)  rows = rows.filter(r => (r.employee_name || r.employee || "").toLowerCase().includes((employee as string).toLowerCase()));
    if (department) rows = rows.filter(r => (r.department || "").toLowerCase().includes((department as string).toLowerCase()));
    if (status)    rows = rows.filter(r => r.status === status);

    // Sort by derived date desc
    rows.sort((a, b) => (b.date || b.creation || "").localeCompare(a.date || a.creation || ""));

    // Paginate
    const pageNum = Number(page);
    const pageSize = Number(limit);
    const start = pageNum * pageSize;
    const paged = rows.slice(start, start + pageSize + 1);
    const hasMore = paged.length > pageSize;

    res.json({ reports: paged.slice(0, pageSize), hasMore, total: rows.length });
  } catch (e) {
    res.status(500).json({ error: String(e) });
  }
});

// ─── Create New Daily Report ─────────────────────────────────────────────────
router.post("/daily-reporting", async (req, res) => {
  if (!isConfigured()) return res.status(503).json({ error: "ERPNext not configured" });

  const { employee_name, date, activities = [] } = req.body;
  if (!employee_name || !date) return res.status(400).json({ error: "employee_name and date are required" });

  try {
    const docData: any = {
      doctype: "Daily Reporting",
      employee_name,
      date,
    };

    // Add activities as child table if provided
    if (Array.isArray(activities) && activities.length > 0) {
      const validRows = activities.filter(a => a.activity || a.project);
      if (validRows.length > 0) {
        docData.daily_reporting_detail = validRows.map((a: any) => ({
          doctype: "Daily Reporting Detail",
          activity: a.activity || "",
          project: a.project || "",
          no_of_hours: parseFloat(a.hours) || 0,
          remarks: a.remarks || "",
        }));
      }
    }

    const r = await fetch(`${ERP_URL}/api/resource/Daily Reporting`, {
      method: "POST",
      headers: { Authorization: auth(), "Content-Type": "application/json" },
      body: JSON.stringify(docData),
    });

    const json = await r.json() as any;
    if (!r.ok) return res.status(r.status).json({ error: json.exception || json.message || "Failed to create" });

    res.json({ name: json.data?.name, success: true });
  } catch (e) {
    res.status(500).json({ error: String(e) });
  }
});

// ─── Serve a temporarily stored PDF ───────────────────────────────────────────
router.get("/daily-reporting/pdf/:id", (req, res) => {
  const entry = pdfStore.get(req.params.id);
  if (!entry) return res.status(404).json({ error: "PDF not found or expired" });
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `inline; filename="${entry.filename}"`);
  res.send(entry.buf);
});

// ─── Send Report as PDF via WhatsApp (UltraMsg) ────────────────────────────────
router.post("/daily-reporting/:name/send-whatsapp", async (req, res) => {
  if (!isConfigured()) return res.status(503).json({ error: "ERPNext not configured" });

  const { name } = req.params;
  const to: string = req.body.to || REPORT_WHATSAPP_TO;

  try {
    // Fetch full document from ERPNext
    const r = await fetch(`${ERP_URL}/api/resource/Daily Reporting/${encodeURIComponent(name)}`, {
      headers: { Authorization: auth() },
    });
    if (!r.ok) return res.status(r.status).json({ error: "Report not found" });
    const json = await r.json() as { data: any };
    const report = json.data;

    // Generate PDF
    const pdfBuf = await generateReportPDF(report);
    const id = randomUUID();
    const empName = (report.employee_name || report.employee || "report").replace(/\s+/g, "_");
    const dateTag = (report.date || new Date().toISOString().slice(0, 10)).replace(/-/g, "");
    const filename = `DailyReport_${empName}_${dateTag}.pdf`;
    pdfStore.set(id, { buf: pdfBuf, filename, expires: Date.now() + 5 * 60_000 });

    // Build a publicly accessible URL using the Replit dev domain
    const host = process.env.REPLIT_DEV_DOMAIN
      ? `https://${process.env.REPLIT_DEV_DOMAIN}`
      : `http://localhost:${process.env.PORT || 8080}`;
    const pdfUrl = `${host}/api/daily-reporting/pdf/${id}`;

    const dept = (report.department || "").replace(/ - WTT$/i, "");
    const dateStr = report.date
      ? new Date(report.date + "T00:00:00").toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" })
      : "";
    const caption = [`Daily Report — ${report.employee_name || report.employee || ""}`,
      dept, dateStr, `Status: ${report.status || "Draft"}`].filter(Boolean).join("  |  ");

    const result = await sendWhatsAppDocument(to, pdfUrl, filename, caption);

    if (result.success) {
      res.json({ success: true, to, filename });
    } else {
      res.status(502).json({ success: false, error: result.error || "WhatsApp send failed" });
    }
  } catch (e) {
    res.status(500).json({ error: String(e) });
  }
});

// ─── MD Reporting employees (mirrors frontend list) ───────────────────────────
const MD_EMPLOYEES = [
  { id: "WTT1199", name: "GOKUL R"        },
  { id: "WTT1606", name: "GOKUL S"        },
  { id: "WTT1278", name: "RAGHUL RAJ D"   },
  { id: "WTT947",  name: "RAJA A"         },
  { id: "WTT1194", name: "SATHISHKUMAR G" },
  { id: "WTT1619", name: "SHOBANA P"      },
  { id: "WTT1211", name: "SIVAKUMAR P"    },
  { id: "WTT1603", name: "SIVAKUMAR M"    },
  { id: "WTT1502", name: "VIGNESH S"      },
];
const MD_IDS   = new Set(MD_EMPLOYEES.map(e => e.id.toUpperCase()));
const MD_NAMES = new Set(MD_EMPLOYEES.map(e => e.name.toUpperCase()));

function matchesMdEmployee(empId: string, empName: string): boolean {
  const id = (empId || "").toUpperCase().trim();
  const name = (empName || "").toUpperCase().trim();
  if (MD_IDS.has(id)) return true;
  if (MD_NAMES.has(name)) return true;
  return MD_EMPLOYEES.some(e => name.includes(e.name.toUpperCase()) || e.name.toUpperCase().includes(name));
}

// ─── Combined Daily Report PDF ────────────────────────────────────────────────
function generateCombinedPDF(
  date: string,
  reported: Array<{ employee: string; employee_name: string; department: string; status: string; date: string; activities?: any[] }>,
  notReported: Array<{ id: string; name: string }>,
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 40, bufferPages: true });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const dateStr = date
      ? new Date(date + "T00:00:00").toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" })
      : new Date().toLocaleDateString("en-GB");

    const total = MD_EMPLOYEES.length;
    const reportedCount = reported.length;

    // ── Header band ──
    doc.rect(0, 0, doc.page.width, 75).fill("#1a3a5c");
    doc.fillColor("white").fontSize(20).font("Helvetica-Bold")
      .text("Daily Report Summary", 40, 16);
    doc.fontSize(10).font("Helvetica")
      .text(`WTT International  ·  ${dateStr}`, 40, 42);
    doc.fontSize(9).fillColor("#93c5fd")
      .text(`${reportedCount} of ${total} employees reported  ·  Generated ${new Date().toLocaleString("en-GB")}`, 40, 58);

    doc.y = 90;

    // ── Coverage bar ──
    const barX = 40, barW = doc.page.width - 80, barH = 10;
    doc.roundedRect(barX, doc.y, barW, barH, 5).fill("#e2e8f0");
    const filled = reportedCount / total;
    if (filled > 0) doc.roundedRect(barX, doc.y, barW * filled, barH, 5).fill("#22c55e");
    doc.y += barH + 14;

    function sectionHeader(title: string, color: string) {
      doc.moveDown(0.4);
      doc.fillColor(color).fontSize(11).font("Helvetica-Bold").text(title.toUpperCase());
      doc.moveTo(40, doc.y + 2).lineTo(doc.page.width - 40, doc.y + 2)
        .strokeColor(color).lineWidth(1.2).stroke();
      doc.moveDown(0.5);
    }

    // ── Reported employees ──
    if (reported.length > 0) {
      sectionHeader(`Reported  (${reported.length})`, "#15803d");
      reported.forEach((r, i) => {
        const isSubmitted = r.status === "Submitted";
        const rowY = doc.y;
        // Status indicator dot
        doc.circle(50, rowY + 7, 4).fill(isSubmitted ? "#22c55e" : "#f59e0b");
        // Name + details
        doc.fillColor("#1e293b").fontSize(10).font("Helvetica-Bold")
          .text(r.employee_name || r.employee, 62, rowY, { width: 200 });
        const dept = (r.department || "").replace(/ - WTT$/i, "");
        if (dept) {
          doc.fillColor("#64748b").fontSize(8.5).font("Helvetica")
            .text(dept, 62, rowY + 13, { width: 200 });
        }
        // Status badge
        const badgeColor = isSubmitted ? "#dcfce7" : "#fef3c7";
        const badgeText = isSubmitted ? "SUBMITTED" : "DRAFT";
        const badgeTxtColor = isSubmitted ? "#166534" : "#92400e";
        const badgeX = doc.page.width - 140;
        doc.roundedRect(badgeX, rowY + 2, 80, 14, 3).fill(badgeColor);
        doc.fillColor(badgeTxtColor).fontSize(8).font("Helvetica-Bold")
          .text(badgeText, badgeX, rowY + 5, { width: 80, align: "center" });

        // Activities if present
        if (r.activities && r.activities.length > 0) {
          let actY = rowY + (dept ? 26 : 18);
          r.activities.slice(0, 3).forEach(act => {
            const text = [act.activity, act.project ? `(${act.project})` : "", act.no_of_hours ? `${act.no_of_hours}h` : ""].filter(Boolean).join("  ");
            doc.fillColor("#475569").fontSize(8).font("Helvetica").text(`  • ${text}`, 68, actY, { width: doc.page.width - 120 });
            actY += 11;
          });
          if (r.activities.length > 3) {
            doc.fillColor("#94a3b8").fontSize(7.5).text(`  + ${r.activities.length - 3} more`, 68, actY);
          }
          doc.y = Math.max(doc.y, actY + 14);
        } else {
          doc.y = rowY + (dept ? 30 : 22);
        }
        if (i < reported.length - 1) {
          doc.moveTo(62, doc.y + 2).lineTo(doc.page.width - 40, doc.y + 2).strokeColor("#f1f5f9").lineWidth(0.5).stroke();
          doc.y += 6;
        }
      });
    }

    // ── Not reported employees ──
    if (notReported.length > 0) {
      doc.moveDown(0.8);
      sectionHeader(`Not Reported  (${notReported.length})`, "#dc2626");
      notReported.forEach((emp, i) => {
        const rowY = doc.y;
        doc.circle(50, rowY + 7, 4).fill("#ef4444");
        doc.fillColor("#1e293b").fontSize(10).font("Helvetica-Bold")
          .text(emp.name, 62, rowY, { width: 200 });
        doc.fillColor("#94a3b8").fontSize(8.5).font("Helvetica")
          .text(emp.id, 62, rowY + 13, { width: 100 });
        // "NOT REPORTED" badge
        const badgeX = doc.page.width - 150;
        doc.roundedRect(badgeX, rowY + 2, 100, 14, 3).fill("#fee2e2");
        doc.fillColor("#991b1b").fontSize(8).font("Helvetica-Bold")
          .text("NOT REPORTED", badgeX, rowY + 5, { width: 100, align: "center" });
        doc.y = rowY + 30;
        if (i < notReported.length - 1) {
          doc.moveTo(62, doc.y - 4).lineTo(doc.page.width - 40, doc.y - 4).strokeColor("#fee2e2").lineWidth(0.5).stroke();
        }
      });
    }

    // ── Footer ──
    const footerY = doc.page.height - 35;
    doc.rect(0, footerY - 5, doc.page.width, 40).fill("#f8fafc");
    doc.fillColor("#94a3b8").fontSize(8).font("Helvetica")
      .text(`FlowMatriX Daily Summary  ·  WTT International  ·  ${dateStr}`,
        40, footerY, { align: "center", width: doc.page.width - 80 });

    doc.end();
  });
}

// ─── Send Combined Daily Summary to WhatsApp ──────────────────────────────────
router.post("/daily-reporting/send-combined", async (req, res) => {
  if (!isConfigured()) return res.status(503).json({ error: "ERPNext not configured" });

  const date: string = req.body.date || new Date().toISOString().split("T")[0];
  const to: string = req.body.to || REPORT_WHATSAPP_TO;

  try {
    // 1. Fetch all reports for the date from ERP
    const fields = JSON.stringify(["name","employee","employee_name","department","docstatus","modified","creation"]);
    const params = new URLSearchParams({ fields, limit_page_length: "500", limit_start: "0", order_by: "creation desc" });
    const r = await fetch(`${ERP_URL}/api/resource/Daily Reporting?${params}`, {
      headers: { Authorization: auth() },
    });
    if (!r.ok) {
      const text = await r.text().catch(() => "");
      return res.status(r.status).json({ error: `ERPNext error: ${text.slice(0, 300)}` });
    }
    const json = await r.json() as { data: any[] };
    let rows: any[] = (json.data || []).map(row => ({
      ...row,
      date: row.name?.match(/(\d{4}-\d{2}-\d{2})/)?.[1] || row.creation?.split(" ")[0] || null,
      status: mapDocStatus(row.docstatus),
    }));

    // 2. Filter to today's date and MD employees
    const dateRows = rows.filter(row => row.date === date && matchesMdEmployee(row.employee, row.employee_name));

    // 3. Fetch full details (activities) for each reported doc in parallel (up to 9 docs)
    const detailed = await Promise.all(dateRows.map(async row => {
      try {
        const dr = await fetch(`${ERP_URL}/api/resource/Daily Reporting/${encodeURIComponent(row.name)}`, {
          headers: { Authorization: auth() },
        });
        if (!dr.ok) return row;
        const dj = await dr.json() as { data: any };
        const activities: any[] = dj.data?.daily_reporting_detail || [];
        return { ...row, activities };
      } catch {
        return row;
      }
    }));

    // 4. Determine which MD employees haven't filed a report
    const notReported = MD_EMPLOYEES.filter(emp =>
      !detailed.some(r => matchesMdEmployee(r.employee, r.employee_name) && (
        (r.employee || "").toUpperCase() === emp.id.toUpperCase() ||
        (r.employee_name || "").toUpperCase().includes(emp.name.toUpperCase()) ||
        emp.name.toUpperCase().includes((r.employee_name || "").toUpperCase())
      ))
    );

    // 5. Generate combined PDF
    const pdfBuf = await generateCombinedPDF(date, detailed, notReported);
    const id = randomUUID();
    const dateTag = date.replace(/-/g, "");
    const filename = `DailySummary_${dateTag}.pdf`;
    pdfStore.set(id, { buf: pdfBuf, filename, expires: Date.now() + 10 * 60_000 });

    // 6. Build a publicly accessible URL
    const host = process.env.REPLIT_DEV_DOMAIN
      ? `https://${process.env.REPLIT_DEV_DOMAIN}`
      : `http://localhost:${process.env.PORT || 8080}`;
    const pdfUrl = `${host}/api/daily-reporting/pdf/${id}`;

    const dateStr = new Date(date + "T00:00:00").toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" });
    const caption = `Daily Report Summary — ${dateStr}\nWTT International`;

    const result = await sendWhatsAppDocument(to, pdfUrl, filename, caption);

    if (result.success) {
      res.json({ success: true, to, filename, reported: detailed.length, notReported: notReported.length });
    } else {
      res.status(502).json({ success: false, error: result.error || "WhatsApp send failed" });
    }
  } catch (e) {
    res.status(500).json({ error: String(e) });
  }
});

// ─── Single Daily Report Detail ───────────────────────────────────────────────
// Single document fetch uses a different Frappe endpoint that doesn't have the
// same field-name restrictions as get_list.
router.get("/daily-reporting/:name", async (req, res) => {
  if (!isConfigured()) return res.status(503).json({ error: "ERPNext not configured" });

  const { name } = req.params;
  try {
    const r = await fetch(`${ERP_URL}/api/resource/Daily Reporting/${encodeURIComponent(name)}`, {
      headers: { Authorization: auth() },
    });

    if (!r.ok) return res.status(r.status).json({ error: "Report not found" });

    const json = await r.json() as { data: any };
    res.json({ report: json.data });
  } catch (e) {
    res.status(500).json({ error: String(e) });
  }
});

export default router;
