import { Router, type IRouter } from "express";
import healthRouter from "./health";
import pmRouter from "./pm";
import meetingMinutesRouter from "./meeting-minutes";
import spreadsheetsRouter from "./spreadsheets";
import authRouter from "./auth";
import pidAnalyzeRouter from "./pid-analyze";
import aiSearchRouter from "./ai-search";
import hrmsRouter from "./hrms";
import projectBoardRouter from "./project-board";
import emailRouter from "./email";
import emailSettingsRouter from "./emailSettings";
import chatRouter from "./chat";
import incidentsRouter from "./incidents";
import drawingsRouter from "./drawings";
import timelineRouter from "./timeline";
import siteDataRouter from "./site-data";
import smartEmailRouter from "./smart-email";
import emailSyncRouter from "./email-sync";
import marketingRouter from "./marketing";
import purchaseDashboardRouter from "./purchase-dashboard";
import storesDashboardRouter from "./stores-dashboard";
import paymentTrackerRouter from "./payment-tracker";
import misReportRouter from "./mis-report";
import cctvRouter from "./cctv";
import calendarRouter from "./calendar";
import notificationsRouter from "./notifications";
import performanceRouter from "./performance";
import dailyReportingRouter from "./daily-reporting";
import logisticsDashboardRouter from "./logistics-dashboard";
import processProposalRouter from "./process-proposal";
import financeDashboardRouter from "./finance-dashboard";
import civilDrawingRouter from "./civil-drawing";
import stockReportsRouter from "./stock-reports";

const router: IRouter = Router();

router.use(authRouter);
router.use(healthRouter);
router.use(pmRouter);
router.use(meetingMinutesRouter);
router.use("/spreadsheets", spreadsheetsRouter);
router.use(pidAnalyzeRouter);
router.use(aiSearchRouter);
router.use(hrmsRouter);
router.use(projectBoardRouter);
router.use(emailRouter);
router.use(emailSettingsRouter);
router.use(chatRouter);
router.use(incidentsRouter);
router.use(drawingsRouter);
router.use(timelineRouter);
router.use(siteDataRouter);
router.use(smartEmailRouter);
router.use(emailSyncRouter);
router.use(marketingRouter);
router.use(purchaseDashboardRouter);
router.use(storesDashboardRouter);
router.use(paymentTrackerRouter);
router.use(misReportRouter);
router.use("/cctv", cctvRouter);
router.use(calendarRouter);
router.use(notificationsRouter);
router.use(performanceRouter);
router.use(dailyReportingRouter);
router.use(logisticsDashboardRouter);
router.use(processProposalRouter);
router.use(financeDashboardRouter);
router.use(civilDrawingRouter);
router.use(stockReportsRouter);

export default router;
